create table employee (
       id bigint generated by default as identity,
        designation varchar(255),
        email_id varchar(255) not null,
        full_name varchar(255) not null,
        hobbies varchar(255),
        hometown varchar(255) not null,
        postgrad_institute varchar(255),
        postgrad_passyear integer,
        skills varchar(255),
        undergrad_college varchar(255) not null,
        undergrad_passyear integer not null,
        work_city varchar(255),
        primary key (id)
    );

create table employer (
       id bigint generated by default as identity,
        from_year integer not null,
        location varchar(255) not null,
        name varchar(255) not null,
        to_year integer not null,
        employee_id bigint,
        primary key (id)
    );

create table job_post (
       id bigint generated by default as identity,
        designation varchar(255) not null,
        location varchar(255) not null,
        rank integer,
        verticle varchar(255) not null,
        primary key (id)
    );


alter table employee 
       add constraint UK_af534w03av8srcldugewrmpbi unique (email_id);

alter table employer 
       add constraint FKmg5dd9mb7tyqn8ejt4h6xp1oc 
       foreign key (employee_id) 
       references employee;       